"""added a archivetable model

Revision ID: 23e7419d6e13
Revises: 32c6d424eb31
Create Date: 2020-07-24 03:29:50.727326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e7419d6e13'
down_revision = '32c6d424eb31'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
