"""added a archivetable model2

Revision ID: 2e7f67bb55aa
Revises: 5c1de05e9881
Create Date: 2020-07-24 03:45:14.618390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e7f67bb55aa'
down_revision = '5c1de05e9881'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archivetbls', sa.Column('text1', sa.String(), nullable=True))
    op.add_column('archivetbls', sa.Column('text2', sa.String(), nullable=True))
    op.drop_column('archivetbls', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archivetbls', sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('archivetbls', 'text2')
    op.drop_column('archivetbls', 'text1')
    # ### end Alembic commands ###
