"""mod 4

Revision ID: 4b880b34ced0
Revises: 2e7f67bb55aa
Create Date: 2020-07-24 04:06:32.233867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b880b34ced0'
down_revision = '2e7f67bb55aa'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archivetbls', sa.Column('filetype', sa.Integer(), nullable=True))
    op.add_column('archivetbls', sa.Column('path', sa.String(), nullable=True))
    op.add_column('archivetbls', sa.Column('username', sa.String(), nullable=True))
    op.drop_column('archivetbls', 'text1')
    op.drop_column('archivetbls', 'text2')
    op.drop_column('archivetbls', 'votes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archivetbls', sa.Column('votes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('archivetbls', sa.Column('text2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('archivetbls', sa.Column('text1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('archivetbls', 'username')
    op.drop_column('archivetbls', 'path')
    op.drop_column('archivetbls', 'filetype')
    # ### end Alembic commands ###
