"""added a archivetable model

Revision ID: 5c1de05e9881
Revises: 23e7419d6e13
Create Date: 2020-07-24 03:30:05.918288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1de05e9881'
down_revision = '23e7419d6e13'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
