"""add create date

Revision ID: ee919ece87b4
Revises: 4b880b34ced0
Create Date: 2020-07-24 04:21:26.760980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee919ece87b4'
down_revision = '4b880b34ced0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archivetbls', sa.Column('create_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('archivetbls', 'create_date')
    # ### end Alembic commands ###
